# Generated by Django 4.0.4 on 2022-05-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_rename_estudiante_persona_delete_profesor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='camada',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='nombre',
            new_name='name',
        ),
    ]
